services:
  client-dashboard:
    container_name: headscale-client-dashboard
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - HEADSCALE_URL=${HEADSCALE_URL:-https://headscale.jeisson.top}
      - HEADSCALE_AUTH_KEY=${HEADSCALE_AUTH_KEY:-}
      - CLIENT_HOSTNAME=${CLIENT_HOSTNAME:-laptop}
      - EXIT_NODE=${EXIT_NODE:-100.64.0.4}
      - WEB_PORT=${WEB_PORT:-30701}
    volumes:
      - /var/run/tailscale/tailscaled.sock:/var/run/tailscale/tailscaled.sock
      - /etc/default/tailscaled:/etc/default/tailscaled
      - /etc/systemd/system:/etc/systemd/system
      - /etc/hosts:/etc/hosts:rw
      - ./:/app
    cap_add:
      - NET_ADMIN
    network_mode: host

